### ISSUE TITLE
Write statement on object identification choice

### ISSUE THREAD

**Issue by jtcooper10** [nicholaswharris/swe_proposal#1]
Let's figure out what objects we want to identify with our program. Once we decide on functionality, I'll write it up as a short statement and put it up on the website.

**Comment by nicholaswharris** [comment]
Watermelons? Pumpkins? Melons in general? I don't know. I'm open to whatever though.

**Comment by jtcooper10** [comment]
Maybe we can generalize a bit and say it categorized fruit. What do you guys think?

**Comment by jcclabo** [comment]
I think fruit in general is good. We can teach it different types of fruit so it can identify them, and we can specify which fruits we taught it in the final report.
