### ISSUE TITLE
Build Gantt chart for project

### ISSUE THREAD

**Issue by jtcooper10** [nicholaswharris/swe_proposal#4]
In order to get a Gantt chart put together, we should figure out a good timeline to set "deadlines" for. We have from Sep. 20 to Oct. 20, which is about 4 weeks plus some change.

My suggestion is that we divide that into four 1-week sprints, with "deadlines" being each Monday. That leaves us with ~2 days to do cleanup and polish before the presentation.

What do you guys think?

**Comment by nicholaswharris** [comment]
Great idea. I'm all for it.
